/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package subtitlemanager;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author atulgpt <atlgpt@gmail.com>
 */
public class Settings extends javax.swing.JFrame {

    private JFileChooser mFileChooser;
    private final UserPreferences mUserPreferences = new UserPreferences();

    /**
     * Creates new form Settings
     */
    public Settings() {
        initComponents();
        initComponents2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.ButtonGroup langInfoSettings = new javax.swing.ButtonGroup();
        lookAndFeelbuttonGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        defaultLocTextField = new javax.swing.JTextField();
        openFileMaagerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        yesRadioButton = new javax.swing.JRadioButton();
        noRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        sysLNFRadioButton = new javax.swing.JRadioButton();
        javaLNFRadioButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Settings");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Default location:");

        defaultLocTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultLocTextFieldActionPerformed(evt);
            }
        });

        openFileMaagerButton.setText("Open");
        openFileMaagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMaagerButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Append language info:");

        langInfoSettings.add(yesRadioButton);
        yesRadioButton.setText("Yes");
        yesRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        langInfoSettings.add(noRadioButton);
        noRadioButton.setText("No");
        noRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Look and Feel:");

        lookAndFeelbuttonGroup.add(sysLNFRadioButton);
        sysLNFRadioButton.setText("System");
        sysLNFRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        lookAndFeelbuttonGroup.add(javaLNFRadioButton);
        javaLNFRadioButton.setText("Java");
        javaLNFRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("(Restart Required)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(24, 24, 24)
                                .addComponent(defaultLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(openFileMaagerButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(24, 24, 24)
                                .addComponent(yesRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(noRadioButton)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sysLNFRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(javaLNFRadioButton)
                        .addGap(126, 126, 126))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(306, 306, 306))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(defaultLocTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openFileMaagerButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(yesRadioButton))
                    .addComponent(noRadioButton))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sysLNFRadioButton)
                        .addComponent(javaLNFRadioButton)))
                .addGap(0, 0, 0)
                .addComponent(jLabel4)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void defaultLocTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultLocTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_defaultLocTextFieldActionPerformed

    private void openFileMaagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMaagerButtonActionPerformed
        String dirName = UserPreferences.getDefaultFileLoc();
        if (mFileChooser == null) {
            mFileChooser = new JFileChooser(dirName);
            mFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        }
        mFileChooser.setCurrentDirectory(new File(dirName));
        mFileChooser.showOpenDialog(this);
        File defaultDirectory = mFileChooser.getSelectedFile();
        if (defaultDirectory != null) {
            defaultLocTextField.setText(defaultDirectory.getAbsolutePath());
            UserPreferences.setDefaultFileLoc(defaultDirectory.getAbsolutePath());
        }

    }//GEN-LAST:event_openFileMaagerButtonActionPerformed

    private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
        boolean langInfoChoosen = false;
        int lnfChoosen = UserPreferences.SYS_LOOK_AND_FEEL;
        if (evt.getSource() == yesRadioButton) {
            langInfoChoosen = true;
        } else if (evt.getSource() == noRadioButton) {
            langInfoChoosen = false;
        }
        UserPreferences.setEmbedLangInfo(langInfoChoosen);
        if (evt.getSource() == sysLNFRadioButton) {
            lnfChoosen = UserPreferences.SYS_LOOK_AND_FEEL;
        } else if (evt.getSource() == javaLNFRadioButton) {
            lnfChoosen = UserPreferences.JAVA_LOOK_AND_FEEL;
        }
        UserPreferences.setLookAndFeel(lnfChoosen);
    }//GEN-LAST:event_radioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Settings().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField defaultLocTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton javaLNFRadioButton;
    private javax.swing.ButtonGroup lookAndFeelbuttonGroup;
    private javax.swing.JRadioButton noRadioButton;
    private javax.swing.JButton openFileMaagerButton;
    private javax.swing.JRadioButton sysLNFRadioButton;
    private javax.swing.JRadioButton yesRadioButton;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        this.setVisible(true);
        boolean isLangInfoChoosen = UserPreferences.isEmbedLangInfo();
        if (isLangInfoChoosen) {
            yesRadioButton.setSelected(isLangInfoChoosen);
        } else {
            noRadioButton.setSelected(!isLangInfoChoosen);
        }
        defaultLocTextField.setText(UserPreferences.getDefaultFileLoc());
        if (UserPreferences.getLookAndFeel() == UserPreferences.SYS_LOOK_AND_FEEL) {
            sysLNFRadioButton.setSelected(true);
        } else if (UserPreferences.getLookAndFeel() == UserPreferences.JAVA_LOOK_AND_FEEL) {
            javaLNFRadioButton.setSelected(true);
        }
    }

}
